//! Genesis vesting (`docs/superpowers/specs/2026-09-28-genesis-vesting-design.md`): timelocked
//! RAND for the team, investors and founding partners.
//!
//! A shielded note cannot be held back — a spend proof hides which note it consumes — so a
//! locked allocation lives *outside* the pool, in this public register seeded by the genesis
//! `vesting` section, and enters the pool only as it unlocks: a `ClaimVested` (signed by the
//! entry's beneficiary) pays the unlocked part into a note, a `RevokeVesting` (signed by a
//! threshold of the entry's revokers) pays the unvested part to the treasury the entry names in
//! genesis — and to no other address — and freezes the entry at what the schedule had released
//! by the block that applies it. The schedule is a cliff, then linear, on the applying block's
//! timestamp.
//!
//! Genesis-gated: a chain without the section has no register (`Ledger::vesting` is `None`)
//! and every one of the four actions is refused `UnsupportedAction("vesting")`.

use super::{staking, Ledger, TxError};
use crate::confidential::ConfidentialExecutor;
use crate::crypto::{merkle_root, Address, Hash, PublicKey, Signature, PUBLIC_KEY_LEN};
use crate::gas;
use crate::notes::{Envelope, ShieldedAddress, Word8, KEM_EK_BYTES};
use crate::types::actions::{
    bond_vested_message, claim_vested_message, revoke_vesting_message, unbond_vested_message, Registration, RevokerSignature,
};
use crate::types::transaction::{Action, Transaction};
use serde::{Deserialize, Serialize};

/// What an allocation is for. Reporting only (`rand_getVestingSummary`): no rule reads it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Class {
    Team,
    Investor,
    Partner,
    Other,
}

impl Class {
    pub fn as_str(&self) -> &'static str {
        match self {
            Class::Team => "team",
            Class::Investor => "investor",
            Class::Partner => "partner",
            Class::Other => "other",
        }
    }

    fn byte(&self) -> u8 {
        match self {
            Class::Team => 0,
            Class::Investor => 1,
            Class::Partner => 2,
            Class::Other => 3,
        }
    }
}

/// One allocation as the genesis file lists it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VestingEntryConfig {
    /// 32 bytes, 64 hex characters; chosen at random by the cut tooling. Never a name.
    #[serde(with = "crate::bridge::state::hex_bytes32")]
    pub id: [u8; 32],
    pub class: Class,
    /// The Dilithium2 key that signs claims — generated by the holder, who sends only this.
    pub beneficiary: PublicKey,
    /// The Dilithium2 keys that may revoke the unvested part, `threshold` of them together
    /// (audit v6, STAKE-3): at most [`MAX_REVOKERS`], distinct, none the beneficiary's. Empty or
    /// absent: irrevocable. A revoke names its signers by their position in this list.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub revokers: Vec<PublicKey>,
    /// How many of `revokers` must sign a revoke: `1 ..= revokers.len()`, required exactly when
    /// the entry is revocable (no default — a three-key list that silently meant 1-of-3 would be
    /// the single-key revoker the audit objected to, three times over).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threshold: Option<u8>,
    /// Where a revoke pays (`rand1…`), required exactly when the entry is revocable (audit v6,
    /// STAKE-3): the revoked part goes to this address and no other, so a stolen revoker quorum
    /// can confiscate to the treasury but cannot pay itself.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub treasury: Option<String>,
    /// Total, in units (1 RAND = 10⁹), a decimal string in the file like every genesis amount
    /// (a plain number is accepted on the way in).
    #[serde(with = "crate::ledger::staking::amount_string")]
    pub amount: u64,
    /// When the lockup starts (network launch, for a sale round).
    pub start_ms: u64,
    /// Nothing unlocks before `start + cliff`.
    pub cliff_ms: u64,
    /// The linear period, *after* the cliff (the SAFT's "C-month cliff, then L-month linear").
    pub linear_ms: u64,
    /// Optional tranche length: unlocks in whole steps (a month for the SAFT's monthly release)
    /// rather than continuously. Must divide `linear_ms`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub step_ms: Option<u64>,
}

impl VestingEntryConfig {
    /// The treasury as the address it names; `None` when absent or not an address (which
    /// [`VestingConfig::check`] refuses for a revocable entry).
    pub fn treasury_address(&self) -> Option<ShieldedAddress> {
        self.treasury.as_deref().and_then(|t| ShieldedAddress::parse(t).ok())
    }
}

/// The most revoker keys one entry may list (audit v6, STAKE-3): a revoke verifies up to this
/// many Dilithium2 signatures, and its indices fit the `u8` bitmask the distinctness check uses.
pub const MAX_REVOKERS: usize = 5;

/// The genesis `vesting` section.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VestingConfig {
    pub entries: Vec<VestingEntryConfig>,
}

impl VestingConfig {
    /// Every rule a file has to meet before it can seed a register; `Ok` is `Σ amount`.
    pub fn check(&self) -> Result<u64, String> {
        if self.entries.is_empty() {
            return Err("no entries".into());
        }
        let mut ids = std::collections::BTreeSet::new();
        let mut total: u64 = 0;
        for e in &self.entries {
            let id = hex::encode(e.id);
            if !ids.insert(e.id) {
                return Err(format!("entry {id} listed twice"));
            }
            if e.amount == 0 {
                return Err(format!("entry {id}: zero amount"));
            }
            if let Some(step) = e.step_ms {
                if step == 0 || e.linear_ms == 0 || e.linear_ms % step != 0 {
                    return Err(format!("entry {id}: the step must be non-zero and divide the linear period"));
                }
            }
            if e.start_ms.checked_add(e.cliff_ms).and_then(|c| c.checked_add(e.linear_ms)).is_none() {
                return Err(format!("entry {id}: start + cliff + linear overflows"));
            }
            if e.beneficiary.as_bytes().len() != PUBLIC_KEY_LEN {
                return Err(format!("entry {id}: beneficiary key is not a Dilithium2 public key"));
            }
            // Audit v6, STAKE-3: a revocable entry names who may revoke (a threshold of distinct
            // keys) and where a revoke pays; an irrevocable one names neither.
            if e.revokers.is_empty() {
                if e.threshold.is_some() || e.treasury.is_some() {
                    return Err(format!("entry {id}: a threshold or a treasury without revokers (an irrevocable entry names neither)"));
                }
            } else {
                if e.revokers.len() > MAX_REVOKERS {
                    return Err(format!("entry {id}: {} revokers, at most {MAX_REVOKERS}", e.revokers.len()));
                }
                for (i, r) in e.revokers.iter().enumerate() {
                    if r.as_bytes().len() != PUBLIC_KEY_LEN {
                        return Err(format!("entry {id}: revoker key {i} is not a Dilithium2 public key"));
                    }
                    if r == &e.beneficiary {
                        return Err(format!("entry {id}: the beneficiary cannot be its own revoker"));
                    }
                    if e.revokers[..i].contains(r) {
                        return Err(format!("entry {id}: revoker key {i} is listed twice"));
                    }
                }
                match e.threshold {
                    Some(t) if t >= 1 && t as usize <= e.revokers.len() => {}
                    Some(t) => return Err(format!("entry {id}: threshold {t} is outside 1..={}", e.revokers.len())),
                    None => return Err(format!("entry {id}: a revocable entry needs a threshold (1..={})", e.revokers.len())),
                }
                match &e.treasury {
                    None => return Err(format!("entry {id}: a revocable entry needs a treasury (the rand1… address a revoke pays)")),
                    Some(t) => {
                        ShieldedAddress::parse(t).map_err(|err| format!("entry {id}: the treasury is not a shielded address: {err}"))?;
                    }
                }
            }
            total = total.checked_add(e.amount).ok_or_else(|| "the entries' total overflows".to_string())?;
        }
        Ok(total)
    }
}

/// One allocation in the register: its genesis terms plus what has happened to it since.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry {
    #[serde(with = "crate::bridge::state::hex_bytes32")]
    pub id: [u8; 32],
    pub class: Class,
    pub beneficiary: PublicKey,
    /// The keys `threshold` of which revoke the entry; empty = irrevocable.
    #[serde(default)]
    pub revokers: Vec<PublicKey>,
    /// 0 exactly when `revokers` is empty.
    #[serde(default)]
    pub threshold: u8,
    /// The one address a revoke may pay; `None` exactly when `revokers` is empty. Text
    /// (`rand1…`) in the persisted register, like a validator's payout in the genesis file.
    #[serde(default, with = "address_text")]
    pub treasury: Option<ShieldedAddress>,
    pub amount: u64,
    pub start_ms: u64,
    pub cliff_ms: u64,
    pub linear_ms: u64,
    #[serde(default)]
    pub step_ms: Option<u64>,
    /// Released to the beneficiary so far, gross (each claim's base included).
    #[serde(default)]
    pub claimed: u64,
    /// What revokes have paid to the treasury so far, gross; 0 until revoked. After the first
    /// revoke the rest of the unvested part (`unvested`) is still in the register, the
    /// treasury's, until a later revoke pays it out.
    #[serde(default)]
    pub revoked_out: u64,
    /// The timestamp of the block that applied the first revoke: the schedule stops there.
    #[serde(default)]
    pub revoked_at: Option<u64>,
    /// What of this entry is bonded as validator stake right now (`BondVested`): still locked,
    /// counted in the validator's `stake`, never claimable until unbonded. Irrevocable entries
    /// only.
    #[serde(default)]
    pub bonded: u64,
    /// The validator `bonded` sits with; `None` whenever `bonded` is 0.
    #[serde(default)]
    pub bonded_to: Option<crate::crypto::Address>,
    /// `UnbondVested` amounts on their way back to the lock, `(release_epoch, amount)`: out of
    /// the validator's stake, not yet claimable (the register's `UNBONDING_EPOCHS`, as a plain
    /// unbond waits). Dropped by the entry's next action once released.
    #[serde(default)]
    pub unbonding: Vec<(u64, u64)>,
    /// Bumped by every accepted action of the entry's *beneficiary* — a claim, a bond, an
    /// unbond: their replay protection.
    #[serde(default)]
    pub nonce: u64,
    /// Bumped by every accepted revoke: the revokers' own replay protection (audit v6, STAKE-4).
    /// Apart from `nonce`, so nothing the beneficiary does can make a signed revoke stale.
    #[serde(default)]
    pub revoke_nonce: u64,
}

/// `Option<ShieldedAddress>` as its `rand1…` text: the register is persisted as JSON, where the
/// derived form would spell the 1 184-byte ML-KEM key as a list of numbers.
mod address_text {
    use crate::notes::ShieldedAddress;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(a: &Option<ShieldedAddress>, s: S) -> Result<S::Ok, S::Error> {
        a.as_ref().map(|a| a.to_string()).serialize(s)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<ShieldedAddress>, D::Error> {
        Option::<String>::deserialize(d)?.map(|t| ShieldedAddress::parse(&t).map_err(serde::de::Error::custom)).transpose()
    }
}

impl Entry {
    fn from_config(c: &VestingEntryConfig) -> Entry {
        Entry {
            id: c.id,
            class: c.class,
            beneficiary: c.beneficiary.clone(),
            revokers: c.revokers.clone(),
            threshold: if c.revokers.is_empty() { 0 } else { c.threshold.unwrap_or(0) },
            treasury: if c.revokers.is_empty() { None } else { c.treasury_address() },
            amount: c.amount,
            start_ms: c.start_ms,
            cliff_ms: c.cliff_ms,
            linear_ms: c.linear_ms,
            step_ms: c.step_ms,
            claimed: 0,
            revoked_out: 0,
            revoked_at: None,
            bonded: 0,
            bonded_to: None,
            unbonding: Vec::new(),
            nonce: 0,
            revoke_nonce: 0,
        }
    }

    /// Whether any key may revoke this entry.
    pub fn is_revocable(&self) -> bool {
        !self.revokers.is_empty()
    }

    /// What still belongs to this entry: neither claimed nor revoked out — whether it sits in
    /// the register or is bonded as a validator's stake.
    pub fn held(&self) -> u64 {
        self.amount.saturating_sub(self.claimed).saturating_sub(self.revoked_out)
    }

    /// What the register itself holds for this entry: `held` less what is bonded (which the
    /// validator register counts). The supply audit's vesting half.
    pub fn in_register(&self) -> u64 {
        self.held().saturating_sub(self.bonded)
    }

    /// What is in the register and free to leave it at `epoch`: not bonded, not still
    /// unbonding.
    pub fn free(&self, epoch: u64) -> u64 {
        let waiting = self.unbonding.iter().filter(|(e, _)| *e > epoch).fold(0u64, |a, (_, v)| a.saturating_add(*v));
        self.in_register().saturating_sub(waiting)
    }

    fn leaf(&self) -> Hash {
        let mut b = Vec::with_capacity(32 + 1 + (1 + self.revokers.len()) * PUBLIC_KEY_LEN + 32 + KEM_EK_BYTES + 8 * 12);
        b.extend_from_slice(&self.id);
        b.push(self.class.byte());
        b.extend_from_slice(self.beneficiary.as_bytes());
        // Audit v6, STAKE-3: who may revoke and where a revoke pays are the entry's terms, so
        // they are in its leaf — the count, the threshold, each key in list order (a revoke
        // names its signers by position), then the treasury behind a presence byte.
        b.push(self.revokers.len() as u8);
        b.push(self.threshold);
        for r in &self.revokers {
            b.extend_from_slice(r.as_bytes());
        }
        match &self.treasury {
            Some(t) => {
                b.push(1);
                b.extend_from_slice(&crate::notes::word8_to_bytes(&t.pk));
                b.extend_from_slice(&(t.kem_ek.len() as u32).to_be_bytes());
                b.extend_from_slice(&t.kem_ek);
            }
            None => b.push(0),
        }
        for w in [self.amount, self.start_ms, self.cliff_ms, self.linear_ms, self.step_ms.unwrap_or(0), self.claimed, self.revoked_out, self.bonded] {
            b.extend_from_slice(&w.to_be_bytes());
        }
        match &self.bonded_to {
            Some(v) => {
                b.push(1);
                b.extend_from_slice(v.as_bytes());
            }
            None => b.push(0),
        }
        b.extend_from_slice(&(self.unbonding.len() as u64).to_be_bytes());
        for (e, v) in &self.unbonding {
            b.extend_from_slice(&e.to_be_bytes());
            b.extend_from_slice(&v.to_be_bytes());
        }
        match self.revoked_at {
            Some(t) => {
                b.push(1);
                b.extend_from_slice(&t.to_be_bytes());
            }
            None => b.push(0),
        }
        b.extend_from_slice(&self.nonce.to_be_bytes());
        b.extend_from_slice(&self.revoke_nonce.to_be_bytes());
        // `-2` since audit v6 (STAKE-3, STAKE-4): the leaf's layout moved, and no chain ever
        // committed to a `-1` leaf (no genesis has carried a `vesting` section).
        Hash::digest_domain(b"rand-vesting-leaf-2", &b)
    }
}

/// The schedule, the SAFT's shape: nothing until `start + cliff`; then `linear` more, either
/// continuously or in whole `step`s (a step unlocks at the *end* of its period, so a 12-month
/// cliff and 18 monthly steps release 1/18 at months 13, 14, …, 30).
///
/// A revoked entry is frozen at what the schedule had released when the revoke applied
/// (`revoked_at`), whatever the time and whatever amount the revoke's note carried (audit v6,
/// STAKE-4). It used to be frozen at `amount − revoked_out`, so whatever the revokers left out
/// of the signed amount — they sign under a margin, because the unvested part shrinks while
/// the revoke travels — vested to the holder at once.
pub fn vested(e: &Entry, t_ms: u64) -> u64 {
    let t_ms = match e.revoked_at {
        Some(at) => t_ms.min(at),
        None => t_ms,
    };
    let cliff = e.start_ms.saturating_add(e.cliff_ms);
    if t_ms < cliff {
        return 0;
    }
    let elapsed = t_ms - cliff;
    if elapsed >= e.linear_ms {
        return e.amount;
    }
    let elapsed = match e.step_ms {
        Some(step) if step > 0 => elapsed - elapsed % step,
        _ => elapsed,
    };
    // elapsed < linear, so the quotient is below `amount` and fits a u64.
    ((e.amount as u128 * elapsed as u128) / e.linear_ms as u128) as u64
}

/// What the beneficiary may claim at `t_ms` in `epoch`: vested and not yet claimed, and in the
/// register and free to leave it (bonded or still-unbonding RAND must come back first).
pub fn claimable(e: &Entry, t_ms: u64, epoch: u64) -> u64 {
    vested(e, t_ms).saturating_sub(e.claimed).min(e.free(epoch))
}

/// What a revoke at `t_ms` could pay the treasury: the part the schedule has not released —
/// for a revoked entry, the part it never will — less what revokes have already paid out.
pub fn unvested(e: &Entry, t_ms: u64) -> u64 {
    e.amount.saturating_sub(vested(e, t_ms)).saturating_sub(e.revoked_out)
}

/// What of the entry is still locked for its holder at `t_ms`: the part not yet vested — and
/// nothing once revoked, when the rest is the treasury's, not the holder's. The public lockup
/// figure (SAFT Schedule 2 §3).
pub fn locked(e: &Entry, t_ms: u64) -> u64 {
    match e.revoked_at {
        Some(_) => 0,
        None => e.amount.saturating_sub(vested(e, t_ms)),
    }
}

/// The register: every entry, in id order, and the net value its claims and revokes have put
/// into the pool (the supply audit's `vesting_released`). Persisted whole, as JSON.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct VestingRegister {
    pub entries: Vec<Entry>,
    /// Σ of the notes claims and revokes created (net of each one's base).
    #[serde(default)]
    pub released: u64,
}

impl VestingRegister {
    pub fn from_config(c: &VestingConfig) -> VestingRegister {
        let mut entries: Vec<Entry> = c.entries.iter().map(Entry::from_config).collect();
        entries.sort_by_key(|a| a.id);
        VestingRegister { entries, released: 0 }
    }

    pub fn get(&self, id: &[u8; 32]) -> Option<&Entry> {
        self.entries.binary_search_by(|e| e.id.cmp(id)).ok().map(|i| &self.entries[i])
    }

    pub fn get_mut(&mut self, id: &[u8; 32]) -> Option<&mut Entry> {
        self.entries.binary_search_by(|e| e.id.cmp(id)).ok().map(move |i| &mut self.entries[i])
    }

    /// What genesis issued into the register.
    pub fn issued(&self) -> u64 {
        self.entries.iter().fold(0u64, |a, e| a.saturating_add(e.amount))
    }

    /// What the register itself holds (bonded RAND is in the validator register's total).
    pub fn in_register(&self) -> u64 {
        self.entries.iter().fold(0u64, |a, e| a.saturating_add(e.in_register()))
    }

    /// What is bonded out of the register to `validator` — stake its own `Unbond` may not touch.
    pub fn bonded_to(&self, validator: &crate::crypto::Address) -> u64 {
        self.entries
            .iter()
            .filter(|e| e.bonded_to.as_ref() == Some(validator))
            .fold(0u64, |a, e| a.saturating_add(e.bonded))
    }

    /// The register's contribution to the state root: its entries' leaves in id order, then
    /// the released counter.
    pub fn root(&self) -> Hash {
        let leaves: Vec<Hash> = self.entries.iter().map(Entry::leaf).collect();
        let mut b = merkle_root(&leaves).as_bytes().to_vec();
        b.extend_from_slice(&(self.entries.len() as u64).to_be_bytes());
        b.extend_from_slice(&self.released.to_be_bytes());
        Hash::digest_domain(b"rand-vesting-root-1", &b)
    }
}

/// Why a vesting action was refused.
#[derive(Debug, thiserror::Error, PartialEq, Eq, Clone)]
pub enum VestingError {
    #[error("vesting entry {0} is not in the register")]
    UnknownEntry(String),
    #[error("wrong nonce: expected {expected}, got {actual}")]
    BadNonce { expected: u64, actual: u64 },
    #[error("bad vesting signature")]
    BadSignature,
    #[error("{amount} does not cover the bundle base {base}")]
    BelowBundleBase { amount: u64, base: u64 },
    #[error("only {available} is vested and unclaimed, cannot claim {want}")]
    NotYetVested { available: u64, want: u64 },
    #[error("the entry has no revoker")]
    NotRevocable,
    #[error("the entry is already revoked and its unvested part paid out")]
    AlreadyRevoked,
    #[error("only {unvested_now} is unvested, cannot revoke {want}")]
    RevokeExceedsUnvested { unvested_now: u64, want: u64 },
    #[error("bad recipient address")]
    BadRecipient,
    /// Audit v6, STAKE-3: a revoke pays the entry's genesis treasury and nothing else.
    #[error("a revoke pays the entry's treasury, not the address it names")]
    NotTheTreasury,
    /// Audit v6, STAKE-3: fewer distinct revokers signed than the entry's threshold.
    #[error("{have} revoker signatures, the entry needs {need}")]
    BelowThreshold { have: usize, need: usize },
    #[error("revoker {0} signed twice")]
    DuplicateRevoker(u8),
    #[error("revoker index {0} is not in the entry's list")]
    BadRevokerIndex(u8),
    #[error("only an irrevocable entry may bond")]
    BondNeedsIrrevocable,
    #[error("the entry is bonded to another validator")]
    BondedElsewhere,
    #[error("only {available} is free to bond, cannot bond {want}")]
    NotFreeToBond { available: u64, want: u64 },
    #[error("only {bonded} is bonded, cannot unbond {want}")]
    NotBonded { bonded: u64, want: u64 },
    #[error("amount must not be zero")]
    ZeroAmount,
    #[error("arithmetic overflow")]
    Overflow,
}

// ------------------------------------------------------------------ the four actions

/// What an action reaching this module that it does not own gets — and what every vesting
/// action gets on a chain without the section: the gate is absolute.
const NOT_VESTING: TxError = TxError::UnsupportedAction("vesting");

fn entry<'a>(ledger: &'a Ledger, id: &[u8; 32]) -> Result<&'a Entry, TxError> {
    let reg = ledger.vesting().ok_or(NOT_VESTING)?;
    reg.get(id).ok_or_else(|| VestingError::UnknownEntry(hex::encode(id)).into())
}

/// The beneficiary's nonce: a claim's, a bond's, an unbond's.
fn check_nonce(e: &Entry, nonce: u64) -> Result<(), VestingError> {
    if nonce != e.nonce {
        return Err(VestingError::BadNonce { expected: e.nonce, actual: nonce });
    }
    Ok(())
}

/// A recipient nobody can seal a note to is not an address (the register's payout rule).
fn check_to(to: &ShieldedAddress) -> Result<(), VestingError> {
    if to.kem_ek.len() != KEM_EK_BYTES {
        return Err(VestingError::BadRecipient);
    }
    Ok(())
}

fn net(amount: u64) -> Result<u64, VestingError> {
    amount.checked_sub(gas::BUNDLE_BASE).filter(|n| *n > 0).ok_or(VestingError::BelowBundleBase { amount, base: gas::BUNDLE_BASE })
}

/// The note a claim or a revoke creates: `to`, no sender, the amount less the base, the native
/// asset, the action's own `time` and blinding — the envelope was sealed against exactly this.
fn release_note(
    to: &ShieldedAddress,
    gross: u64,
    time: u32,
    r: &Word8,
    executor: &dyn ConfidentialExecutor,
) -> Result<Word8, VestingError> {
    Ok(super::mint_commitment(executor, &to.pk, net(gross)?, time, r))
}

/// The note `action` would create, for `Ledger::derived_commitment` (the mempool's conflict
/// index). `None` for a bond or an unbond, which create none, and for an amount that does not
/// cover the base — which `validate` refuses on its own.
pub(super) fn derived_note(action: &Action, executor: &dyn ConfidentialExecutor) -> Option<Word8> {
    match action {
        Action::ClaimVested { amount, to, time, r, .. } => release_note(to, *amount, *time, r, executor).ok(),
        Action::RevokeVesting { unvested, to, time, r, .. } => release_note(to, *unvested, *time, r, executor).ok(),
        _ => None,
    }
}

/// A claim's rules, cheap before expensive, the signature last.
#[allow(clippy::too_many_arguments)]
fn check_claim(
    ledger: &Ledger,
    id: &[u8; 32],
    amount: u64,
    nonce: u64,
    to: &ShieldedAddress,
    time: u32,
    r: &Word8,
    envelope: &Envelope,
    signature: &Signature,
    chain_id: u64,
) -> Result<(), TxError> {
    let e = entry(ledger, id)?;
    check_nonce(e, nonce)?;
    net(amount)?;
    check_to(to)?;
    let available = claimable(e, ledger.timestamp_ms(), ledger.epoch());
    if amount > available {
        return Err(VestingError::NotYetVested { available, want: amount }.into());
    }
    let msg = claim_vested_message(&ledger.signing_domain().genesis, chain_id, id, amount, nonce, to, time, r, envelope);
    if !e.beneficiary.verify(msg.as_bytes(), signature) {
        return Err(VestingError::BadSignature.into());
    }
    Ok(())
}

/// The shape of a revoke's signature list against the entry's revokers (audit v6, STAKE-3),
/// before any signature is verified: no more signatures than keys, every index in the list, no
/// revoker twice, and at least `threshold` of them. All of it is the transaction's bytes against
/// genesis constants.
fn check_revoker_set(e: &Entry, signatures: &[RevokerSignature]) -> Result<(), VestingError> {
    let mut seen = 0u8;
    for s in signatures {
        if s.index as usize >= e.revokers.len() {
            return Err(VestingError::BadRevokerIndex(s.index));
        }
        // `MAX_REVOKERS` is 5, so an index that passed the bound above fits the mask.
        if seen & (1 << s.index) != 0 {
            return Err(VestingError::DuplicateRevoker(s.index));
        }
        seen |= 1 << s.index;
    }
    if signatures.len() < e.threshold as usize {
        return Err(VestingError::BelowThreshold { have: signatures.len(), need: e.threshold as usize });
    }
    Ok(())
}

/// A revoke's rules, cheap before expensive, the signatures last. Audit v6, STAKE-3: the
/// recipient is the entry's genesis treasury and nothing else, and a threshold of the entry's
/// revokers — distinct keys, each over the same message — signs it; before, one key's signature
/// sent the unvested part of every revocable entry to an address that key's holder named.
///
/// Audit v6, STAKE-4. The nonce is the revokers' own (`Entry::revoke_nonce`), which only a
/// revoke moves, so a claim landing first cannot make a signed revoke stale. And the signed
/// `amount` is what the revoke's *note* pays — the least the revokers expect to be unvested,
/// refused if less is: the revoke itself takes the whole unvested part as of the applying
/// block (`vested` stops at `revoked_at`), and what the note does not carry stays in the
/// register, the treasury's, for a later revoke to pay out. The note's amount has to be signed
/// — its envelope is sealed against the note, and a wallet finds a note by opening the envelope
/// and recomputing the commitment — so "no signed amount" would leave the treasury a note its
/// wallet cannot see; a signed minimum plus a sweep leaves the holder no dust and the treasury
/// every unit.
#[allow(clippy::too_many_arguments)]
fn check_revoke(
    ledger: &Ledger,
    id: &[u8; 32],
    amount: u64,
    nonce: u64,
    to: &ShieldedAddress,
    time: u32,
    r: &Word8,
    envelope: &Envelope,
    signatures: &[RevokerSignature],
    chain_id: u64,
) -> Result<(), TxError> {
    let e = entry(ledger, id)?;
    if !e.is_revocable() {
        return Err(VestingError::NotRevocable.into());
    }
    net(amount)?;
    check_to(to)?;
    if e.treasury.as_ref() != Some(to) {
        return Err(VestingError::NotTheTreasury.into());
    }
    check_revoker_set(e, signatures)?;
    if nonce != e.revoke_nonce {
        return Err(VestingError::BadNonce { expected: e.revoke_nonce, actual: nonce }.into());
    }
    // Until the first revoke the unvested part only shrinks with time, so the revokers sign a
    // little less than they saw; from then on it is what is left to pay out, and only a revoke
    // moves it.
    let unvested_now = unvested(e, ledger.timestamp_ms()).min(e.free(ledger.epoch()));
    if e.revoked_at.is_some() && unvested_now == 0 {
        return Err(VestingError::AlreadyRevoked.into());
    }
    if amount > unvested_now {
        return Err(VestingError::RevokeExceedsUnvested { unvested_now, want: amount }.into());
    }
    let msg = revoke_vesting_message(&ledger.signing_domain().genesis, chain_id, id, amount, nonce, to, time, r, envelope);
    // Every listed signature must verify: `check_revoker_set` counted the list, so one bad
    // signature among enough good ones is a refusal, not a smaller quorum.
    for s in signatures {
        if !e.revokers[s.index as usize].verify(msg.as_bytes(), &s.signature) {
            return Err(VestingError::BadSignature.into());
        }
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn check_bond(
    ledger: &Ledger,
    id: &[u8; 32],
    validator: &Address,
    amount: u64,
    registration: Option<&Registration>,
    nonce: u64,
    signature: &Signature,
    chain_id: u64,
) -> Result<(), TxError> {
    let e = entry(ledger, id)?;
    // A revocable grant never bonds, so a revoke never has to reach into a validator's stake.
    if e.is_revocable() {
        return Err(VestingError::BondNeedsIrrevocable.into());
    }
    check_nonce(e, nonce)?;
    if amount == 0 {
        return Err(VestingError::ZeroAmount.into());
    }
    if e.bonded_to.is_some_and(|v| v != *validator) {
        return Err(VestingError::BondedElsewhere.into());
    }
    let available = e.free(ledger.epoch());
    if amount > available {
        return Err(VestingError::NotFreeToBond { available, want: amount }.into());
    }
    // The register's own bond rules: registration exactly when new, signed by the validator,
    // the minimum stake.
    staking::check_bond(ledger, validator, amount, registration, chain_id)?;
    let msg = bond_vested_message(&ledger.signing_domain().genesis, chain_id, id, validator, amount, nonce, registration);
    if !e.beneficiary.verify(msg.as_bytes(), signature) {
        return Err(VestingError::BadSignature.into());
    }
    Ok(())
}

fn check_unbond(
    ledger: &Ledger,
    id: &[u8; 32],
    amount: u64,
    nonce: u64,
    signature: &Signature,
    chain_id: u64,
) -> Result<Address, TxError> {
    let e = entry(ledger, id)?;
    check_nonce(e, nonce)?;
    if amount == 0 {
        return Err(VestingError::ZeroAmount.into());
    }
    let validator = match e.bonded_to {
        Some(v) if amount <= e.bonded => v,
        _ => return Err(VestingError::NotBonded { bonded: e.bonded, want: amount }.into()),
    };
    // Only active stake unbonds, as a plain `Unbond`: what is still queued is not weight yet.
    let v = ledger.validators().get(&validator).ok_or(staking::StakingError::UnknownValidator(validator))?;
    let have = v.stake.saturating_sub(ledger.queued_stake(&validator));
    if amount > have {
        return Err(staking::StakingError::InsufficientStake { have, want: amount }.into());
    }
    let msg = unbond_vested_message(&ledger.signing_domain().genesis, chain_id, id, amount, nonce);
    if !e.beneficiary.verify(msg.as_bytes(), signature) {
        return Err(VestingError::BadSignature.into());
    }
    Ok(validator)
}

/// Admission's half: every rule, and for a claim or a revoke the note must be new.
pub(super) fn validate(
    ledger: &Ledger,
    tx: &Transaction,
    action: &Action,
    executor: &dyn ConfidentialExecutor,
) -> Result<(), TxError> {
    ledger.vesting().ok_or(NOT_VESTING)?;
    let chain_id = tx.chain_id;
    match action {
        Action::ClaimVested { entry, amount, nonce, to, time, r, envelope, signature } => {
            check_claim(ledger, entry, *amount, *nonce, to, *time, r, envelope, signature, chain_id)?;
        }
        Action::RevokeVesting { entry, unvested, nonce, to, time, r, envelope, signatures } => {
            check_revoke(ledger, entry, *unvested, *nonce, to, *time, r, envelope, signatures, chain_id)?;
        }
        Action::BondVested { entry, validator, amount, registration, nonce, signature } => {
            return check_bond(ledger, entry, validator, *amount, registration.as_ref(), *nonce, signature, chain_id);
        }
        Action::UnbondVested { entry, amount, nonce, signature } => {
            return check_unbond(ledger, entry, *amount, *nonce, signature, chain_id).map(|_| ());
        }
        _ => return Err(NOT_VESTING),
    }
    let cm = derived_note(action, executor).ok_or(NOT_VESTING)?;
    if ledger.has_commitment(&cm) {
        return Err(TxError::CommitmentExists(cm));
    }
    Ok(())
}

/// Drop the unbonding rows that have come back by `epoch`: they are plain register value now.
fn settle(e: &mut Entry, epoch: u64) {
    e.unbonding.retain(|(release, _)| *release > epoch);
}

/// The apply step, in lockstep with [`validate`]: every check re-run, everything that can fail
/// worked out before the first mutation.
pub(super) fn apply(
    ledger: &mut Ledger,
    tx: &Transaction,
    action: &Action,
    proposer: &Address,
    executor: &dyn ConfidentialExecutor,
) -> Result<(), TxError> {
    validate(ledger, tx, action, executor)?;
    let now = ledger.timestamp_ms();
    let epoch = ledger.epoch();
    match action {
        Action::ClaimVested { entry, amount, envelope, .. } | Action::RevokeVesting { entry, unvested: amount, envelope, .. } => {
            let cm = derived_note(action, executor).ok_or(NOT_VESTING)?;
            let paid = net(*amount)?;
            let rewards = ledger.validators().get(proposer).ok_or(TxError::UnknownProposer(*proposer))?.rewards;
            rewards.checked_add(gas::BUNDLE_BASE).ok_or(TxError::Overflow)?;
            let reg = ledger.vesting_mut().ok_or(NOT_VESTING)?;
            let released = reg.released.checked_add(paid).ok_or(VestingError::Overflow)?;
            let e = reg.get_mut(entry).expect("validated above");
            if matches!(action, Action::ClaimVested { .. }) {
                e.claimed = e.claimed.checked_add(*amount).ok_or(VestingError::Overflow)?;
                e.nonce += 1;
            } else {
                // The first revoke stops the schedule at this block (STAKE-4): the whole
                // unvested part leaves the holder's reach now, whatever this note carries. A
                // later one only pays out more of it.
                let revoked_out = e.revoked_out.checked_add(*amount).ok_or(VestingError::Overflow)?;
                e.revoked_at.get_or_insert(now);
                e.revoked_out = revoked_out;
                e.revoke_nonce += 1;
            }
            settle(e, epoch);
            reg.released = released;
            ledger.append_deposit(cm, envelope.clone(), executor)?;
            let p = ledger.validators.get_mut(proposer).expect("looked up above");
            p.rewards = p.rewards.checked_add(gas::BUNDLE_BASE).ok_or(TxError::Overflow)?;
        }
        Action::BondVested { entry, validator, amount, registration, .. } => {
            ledger.bond(*validator, *amount, registration.as_ref(), tx.chain_id)?;
            let reg = ledger.vesting_mut().ok_or(NOT_VESTING)?;
            let e = reg.get_mut(entry).expect("validated above");
            e.bonded = e.bonded.checked_add(*amount).ok_or(VestingError::Overflow)?;
            e.bonded_to = Some(*validator);
            e.nonce += 1;
            settle(e, epoch);
        }
        Action::UnbondVested { entry, amount, nonce, signature } => {
            let validator = check_unbond(ledger, entry, *amount, *nonce, signature, tx.chain_id)?;
            let release = epoch.checked_add(staking::UNBONDING_EPOCHS).ok_or(VestingError::Overflow)?;
            let v = ledger.validators.get_mut(&validator).expect("checked above");
            v.stake -= amount;
            let reg = ledger.vesting_mut().ok_or(NOT_VESTING)?;
            let e = reg.get_mut(entry).expect("validated above");
            e.bonded -= amount;
            if e.bonded == 0 {
                e.bonded_to = None;
            }
            settle(e, epoch);
            match e.unbonding.last_mut().filter(|(last, _)| *last == release) {
                Some((_, pending)) => *pending = pending.checked_add(*amount).ok_or(VestingError::Overflow)?,
                None => e.unbonding.push((release, *amount)),
            }
            e.nonce += 1;
        }
        _ => return Err(NOT_VESTING),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::{Address, Keypair};

    pub(crate) fn key(i: u8) -> PublicKey {
        Keypair::from_seed([i; 32]).unwrap().public_key().clone()
    }

    fn treasury() -> ShieldedAddress {
        ShieldedAddress { pk: [9; 8], kem_ek: vec![9; KEM_EK_BYTES] }
    }

    fn cfg(id: u8, amount: u64, start: u64, cliff: u64, linear: u64) -> VestingEntryConfig {
        VestingEntryConfig {
            id: [id; 32],
            class: Class::Investor,
            beneficiary: key(1),
            revokers: vec![key(2)],
            threshold: Some(1),
            treasury: Some(treasury().to_string()),
            amount,
            start_ms: start,
            cliff_ms: cliff,
            linear_ms: linear,
            step_ms: None,
        }
    }

    fn entry(amount: u64, start: u64, cliff: u64, linear: u64) -> Entry {
        Entry::from_config(&cfg(1, amount, start, cliff, linear))
    }

    #[test]
    fn nothing_vests_before_the_cliff_and_the_linear_period_runs_after_it() {
        // 1 200 000 from t = 10 000: a 12 000 ms cliff, then 24 000 ms linear.
        let e = entry(1_200_000, 10_000, 12_000, 24_000);
        assert_eq!(vested(&e, 0), 0);
        assert_eq!(vested(&e, 21_999), 0, "one ms before the cliff");
        assert_eq!(vested(&e, 22_000), 0, "the linear period starts at the cliff");
        assert_eq!(vested(&e, 22_001), 50);
        assert_eq!(vested(&e, 34_000), 600_000, "half way through the linear period");
        assert_eq!(vested(&e, 45_999), 1_199_950);
        assert_eq!(vested(&e, 46_000), 1_200_000);
        assert_eq!(vested(&e, u64::MAX), 1_200_000);
    }

    /// SAFT Schedule 2 §2, the Founding Sale: a 12-month cliff, then 18 monthly tranches that
    /// unlock at months 13 through 30.
    #[test]
    fn monthly_steps_release_one_tranche_at_the_end_of_each_month_after_the_cliff() {
        const MONTH: u64 = 30 * 86_400_000;
        let mut c = cfg(1, 18_000, 0, 12 * MONTH, 18 * MONTH);
        c.step_ms = Some(MONTH);
        let e = Entry::from_config(&c);
        assert_eq!(vested(&e, 12 * MONTH), 0, "month 12: still nothing");
        assert_eq!(vested(&e, 13 * MONTH - 1), 0);
        assert_eq!(vested(&e, 13 * MONTH), 1_000, "month 13: the first tranche");
        assert_eq!(vested(&e, 14 * MONTH - 1), 1_000);
        assert_eq!(vested(&e, 21 * MONTH), 9_000);
        assert_eq!(vested(&e, 30 * MONTH - 1), 17_000);
        assert_eq!(vested(&e, 30 * MONTH), 18_000, "month 30: the last");
    }

    #[test]
    fn a_zero_cliff_with_a_zero_linear_period_unlocks_at_the_start() {
        let e = entry(100, 5, 0, 0);
        assert_eq!(vested(&e, 4), 0);
        assert_eq!(vested(&e, 5), 100);
    }

    #[test]
    fn the_schedule_does_not_overflow_near_u64_max() {
        let e = entry(u64::MAX, 0, 0, 1_000);
        assert_eq!(vested(&e, 500), u64::MAX / 2);
        assert_eq!(vested(&e, 999), ((u64::MAX as u128 * 999) / 1000) as u64);
    }

    #[test]
    fn a_revoked_entry_is_frozen_and_claimable_counts_what_was_claimed() {
        let mut e = entry(1_000, 0, 0, 1_000);
        e.claimed = 100;
        assert_eq!(claimable(&e, 300, 0), 200);
        assert_eq!(unvested(&e, 300), 700);
        assert_eq!(locked(&e, 300), 700);
        // Revoked at t = 300 by a note of 650: the schedule stops at 300, whatever the note
        // carried (STAKE-4) — 50 stay in the register, the treasury's, not the holder's.
        e.revoked_at = Some(300);
        e.revoked_out = 650;
        assert_eq!(vested(&e, 300), 300);
        assert_eq!(vested(&e, 10_000), 300, "frozen at the revoke's block, whatever the time");
        assert_eq!(vested(&e, 200), 200, "and the schedule before it is unchanged");
        assert_eq!(claimable(&e, 10_000, 0), 200);
        assert_eq!(unvested(&e, 10_000), 50, "what a later revoke may still pay the treasury");
        assert_eq!(locked(&e, 10_000), 0, "nothing is locked for the holder any more");
        assert_eq!(e.held(), 250);
        e.revoked_out = 700;
        assert_eq!((unvested(&e, 10_000), claimable(&e, 10_000, 0), e.held()), (0, 200, 200));
    }

    #[test]
    fn bonded_and_unbonding_ram_is_not_claimable_until_it_is_back() {
        let mut e = entry(1_000, 0, 0, 1_000);
        e.bonded = 600;
        assert_eq!((e.held(), e.in_register(), e.free(0)), (1_000, 400, 400));
        assert_eq!(claimable(&e, 2_000, 0), 400, "fully vested, but 600 is stake");
        e.bonded = 100;
        e.unbonding = vec![(5, 500)];
        assert_eq!(claimable(&e, 2_000, 4), 400, "the 500 is still unbonding in epoch 4");
        assert_eq!(claimable(&e, 2_000, 5), 900, "released in epoch 5");
    }

    #[test]
    fn the_config_check_refuses_every_bad_entry() {
        let ok = VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5), cfg(2, 20, 0, 5, 5)] };
        assert_eq!(ok.check(), Ok(30));
        let bad = |c: VestingConfig, what: &str| {
            let e = c.check().unwrap_err();
            assert!(e.contains(what), "{e:?} should mention {what:?}");
        };
        bad(VestingConfig { entries: vec![] }, "no entries");
        bad(VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5), cfg(1, 20, 0, 0, 5)] }, "twice");
        bad(VestingConfig { entries: vec![cfg(1, 0, 0, 0, 5)] }, "zero amount");
        let mut stepped = cfg(1, 10, 0, 0, 5);
        stepped.step_ms = Some(2);
        bad(VestingConfig { entries: vec![stepped.clone()] }, "divide");
        stepped.step_ms = Some(0);
        bad(VestingConfig { entries: vec![stepped] }, "divide");
        bad(VestingConfig { entries: vec![cfg(1, 10, u64::MAX, 1, 0)] }, "overflows");
        bad(VestingConfig { entries: vec![cfg(1, u64::MAX, 0, 0, 5), cfg(2, 1, 0, 0, 5)] }, "total overflows");
        let mut short = cfg(1, 10, 0, 0, 5);
        short.beneficiary = serde_json::from_str::<PublicKey>("\"abcd\"").unwrap();
        bad(VestingConfig { entries: vec![short] }, "beneficiary key");
        let mut short = cfg(1, 10, 0, 0, 5);
        short.revokers = vec![serde_json::from_str::<PublicKey>("\"abcd\"").unwrap()];
        bad(VestingConfig { entries: vec![short] }, "revoker key");
        let mut own = cfg(1, 10, 0, 0, 5);
        own.revokers = vec![own.beneficiary.clone()];
        bad(VestingConfig { entries: vec![own] }, "its own revoker");
        // Audit v6, STAKE-3: the revoker set and the treasury.
        let with = |f: fn(&mut VestingEntryConfig)| {
            let mut c = cfg(1, 10, 0, 0, 5);
            c.revokers = vec![key(2), key(3), key(4)];
            c.threshold = Some(2);
            f(&mut c);
            VestingConfig { entries: vec![c] }
        };
        assert_eq!(with(|_| ()).check(), Ok(10));
        bad(with(|c| c.treasury = None), "needs a treasury");
        bad(with(|c| c.treasury = Some("rand1nonsense".into())), "not a shielded address");
        bad(with(|c| c.threshold = None), "needs a threshold");
        bad(with(|c| c.threshold = Some(0)), "outside 1..=3");
        bad(with(|c| c.threshold = Some(4)), "outside 1..=3");
        bad(with(|c| c.revokers[2] = c.revokers[0].clone()), "listed twice");
        bad(with(|c| c.revokers = (2..8).map(key).collect()), "at most 5");
        bad(with(|c| c.revokers.clear()), "without revokers");
        let mut irrevocable = cfg(1, 10, 0, 0, 5);
        (irrevocable.revokers, irrevocable.threshold, irrevocable.treasury) = (Vec::new(), None, None);
        assert_eq!(VestingConfig { entries: vec![irrevocable] }.check(), Ok(10));
    }

    #[test]
    fn the_register_sorts_by_id_and_its_root_moves_with_every_field() {
        let c = VestingConfig { entries: vec![cfg(9, 10, 0, 0, 5), cfg(3, 20, 0, 0, 5)] };
        let r = VestingRegister::from_config(&c);
        assert_eq!(r.entries[0].id, [3; 32]);
        assert_eq!(r.get(&[9; 32]).unwrap().amount, 10);
        assert!(r.get(&[4; 32]).is_none());
        assert_eq!((r.issued(), r.in_register()), (30, 30));
        let base = r.root();
        let mutations: Vec<fn(&mut VestingRegister)> = vec![
            |r| r.entries[0].claimed += 1,
            |r| r.entries[0].revoked_out += 1,
            |r| r.entries[0].revoked_at = Some(0),
            |r| r.entries[0].nonce += 1,
            |r| r.entries[0].revoke_nonce += 1,
            |r| r.entries[0].amount += 1,
            |r| r.entries[0].start_ms += 1,
            |r| r.entries[0].cliff_ms += 1,
            |r| r.entries[0].linear_ms += 1,
            |r| r.entries[0].step_ms = Some(1),
            |r| r.entries[0].class = Class::Team,
            |r| r.entries[0].revokers.clear(),
            |r| r.entries[0].revokers.push(key(8)),
            |r| r.entries[0].revokers[0] = key(8),
            |r| r.entries[0].threshold += 1,
            |r| r.entries[0].treasury = None,
            |r| r.entries[0].treasury.as_mut().unwrap().pk[0] ^= 1,
            |r| r.entries[0].treasury.as_mut().unwrap().kem_ek[0] ^= 1,
            |r| r.entries[0].beneficiary = key(7),
            |r| r.entries[0].bonded += 1,
            |r| r.entries[0].bonded_to = Some(Address([1; 32])),
            |r| r.entries[0].unbonding.push((1, 1)),
            |r| r.released += 1,
        ];
        for (i, m) in mutations.into_iter().enumerate() {
            let mut x = r.clone();
            m(&mut x);
            assert_ne!(x.root(), base, "mutation {i} must move the root");
        }
    }

    #[test]
    fn the_genesis_form_round_trips_as_json() {
        let c = VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5)] };
        let json = serde_json::to_string(&c).unwrap();
        assert!(json.contains("\"class\":\"investor\""));
        assert!(!json.contains("step_ms"), "an absent step is omitted");
        assert_eq!(serde_json::from_str::<VestingConfig>(&json).unwrap(), c);
        let r = VestingRegister::from_config(&c);
        assert_eq!((r.entries[0].threshold, r.entries[0].treasury.clone()), (1, Some(treasury())), "the register holds the parsed terms");
        let stored = serde_json::to_string(&r).unwrap();
        assert!(stored.contains(&format!("\"treasury\":\"{}\"", treasury())), "the persisted treasury is its rand1… text");
        assert_eq!(serde_json::from_str::<VestingRegister>(&stored).unwrap(), r);
        // The one-key `revoker` field this section had before audit v6 is refused, not ignored:
        // read as an unknown key it would have made a revocable grant irrevocable.
        let old = json.replace("\"revokers\":[", "\"revoker\":[");
        assert!(serde_json::from_str::<VestingConfig>(&old).unwrap_err().to_string().contains("unknown field"));
    }
}

/// The four actions against a real ledger (spec §10).
#[cfg(test)]
mod ledger_tests {
    use super::*;
    use crate::confidential::StubExecutor;
    use crate::crypto::Keypair;
    use crate::ledger::staking::{StakingError, MIN_STAKE};
    use crate::ledger::ValidatorEntry;
    use crate::types::actions::registration_message;
    use std::collections::BTreeMap;

    const CHAIN: u64 = 7;
    const BASE: u64 = gas::BUNDLE_BASE;
    const U: u64 = crate::ledger::staking::MIN_STAKE; // 1 000 RAND: one unit of vesting, one minimum stake

    fn kp(i: u8) -> Keypair {
        Keypair::from_seed([i; 32]).unwrap()
    }
    fn addr(i: u8) -> ShieldedAddress {
        ShieldedAddress { pk: [i as u32; 8], kem_ek: vec![i; KEM_EK_BYTES] }
    }
    fn env() -> Envelope {
        Envelope { kem_ct: vec![1; 8], to_receiver: vec![2; 4], to_sender: vec![3; 4], body: vec![4; 16] }
    }
    const HOLDER: u8 = 1;
    /// The revocable entries' three revoker keys, by seed, in list order; two of them revoke.
    const REVOKERS: [u8; 3] = [2, 3, 4];
    const TREASURY: u8 = 77;
    const PROPOSER: u8 = 90;

    /// An entry of `10 U` from t = 1 000: cliff 1 000 ms, then 10 000 ms linear, so `U` a
    /// thousand ms from t = 2 000 on.
    fn cfg(id: u8, revocable: bool) -> VestingEntryConfig {
        VestingEntryConfig {
            id: [id; 32],
            class: if revocable { Class::Team } else { Class::Investor },
            beneficiary: kp(HOLDER).public_key().clone(),
            revokers: if revocable { REVOKERS.iter().map(|s| kp(*s).public_key().clone()).collect() } else { Vec::new() },
            threshold: revocable.then_some(2),
            treasury: revocable.then(|| addr(TREASURY).to_string()),
            amount: 10 * U,
            start_ms: 1_000,
            cliff_ms: 1_000,
            linear_ms: 10_000,
            step_ms: None,
        }
    }

    fn ledger(entries: Vec<VestingEntryConfig>, t: u64) -> Ledger {
        let p = kp(PROPOSER);
        let mut reg = BTreeMap::new();
        reg.insert(
            p.address(),
            ValidatorEntry {
                public_key: p.public_key().clone(),
                stake: MIN_STAKE,
                pending: Vec::new(),
                rewards: 0,
                payout: addr(PROPOSER),
                nonce: 0,
                activation_epoch: 0,
            },
        );
        let mut l = Ledger::new(CHAIN, [11; 8], reg, &StubExecutor);
        l.set_epoch_blocks(4);
        l.set_height(5);
        l.set_timestamp_ms(t);
        l.set_genesis_supply(0, MIN_STAKE);
        l.set_vesting(Some(VestingRegister::from_config(&VestingConfig { entries })));
        l
    }

    fn g(l: &Ledger) -> Hash {
        l.signing_domain().genesis
    }

    fn tx(action: Action) -> Transaction {
        Transaction { chain_id: CHAIN, bundle: None, action }
    }

    fn claim(l: &Ledger, id: u8, amount: u64, nonce: u64, signer: u8, r: u8) -> Transaction {
        let (to, time, r) = (addr(HOLDER), l.height() as u32, [r as u32; 8]);
        let m = claim_vested_message(&g(l), CHAIN, &[id; 32], amount, nonce, &to, time, &r, &env());
        let signature = kp(signer).sign(m.as_bytes());
        tx(Action::ClaimVested { entry: [id; 32], amount, nonce, to, time, r, envelope: env(), signature })
    }

    /// A revoke to `to`, signed by `signers`: each `(index, key seed)` — the position the
    /// signature claims in the entry's list and the key that actually signs.
    fn revoke_to(l: &Ledger, id: u8, unvested: u64, nonce: u64, to: ShieldedAddress, signers: &[(u8, u8)]) -> Transaction {
        let (time, r) = (l.height() as u32, [9u32; 8]);
        let m = revoke_vesting_message(&g(l), CHAIN, &[id; 32], unvested, nonce, &to, time, &r, &env());
        let signatures = signers.iter().map(|(index, seed)| RevokerSignature { index: *index, signature: kp(*seed).sign(m.as_bytes()) }).collect();
        tx(Action::RevokeVesting { entry: [id; 32], unvested, nonce, to, time, r, envelope: env(), signatures })
    }

    /// The rightful revoke: to the treasury, signed by the first two revokers.
    fn revoke(l: &Ledger, id: u8, unvested: u64, nonce: u64) -> Transaction {
        revoke_to(l, id, unvested, nonce, addr(TREASURY), &[(0, REVOKERS[0]), (1, REVOKERS[1])])
    }

    fn bond(l: &Ledger, id: u8, validator: &Keypair, amount: u64, nonce: u64, new: bool) -> Transaction {
        let registration = new.then(|| {
            let payout = addr(55);
            let signature = validator.sign(registration_message(CHAIN, &payout).as_bytes());
            Registration { public_key: validator.public_key().clone(), payout, signature }
        });
        let m = bond_vested_message(&g(l), CHAIN, &[id; 32], &validator.address(), amount, nonce, registration.as_ref());
        let signature = kp(HOLDER).sign(m.as_bytes());
        tx(Action::BondVested { entry: [id; 32], validator: validator.address(), amount, registration, nonce, signature })
    }

    fn unbond(l: &Ledger, id: u8, amount: u64, nonce: u64) -> Transaction {
        let signature = kp(HOLDER).sign(unbond_vested_message(&g(l), CHAIN, &[id; 32], amount, nonce).as_bytes());
        tx(Action::UnbondVested { entry: [id; 32], amount, nonce, signature })
    }

    fn apply(l: &mut Ledger, t: &Transaction) -> Result<(), TxError> {
        l.apply_tx(t, &kp(PROPOSER).address(), &StubExecutor).map(|_| ())
    }

    /// Build the transaction against the ledger first, then apply it.
    macro_rules! ap {
        ($l:ident, $t:expr) => {{
            let t = $t;
            apply(&mut $l, &t)
        }};
    }

    fn verr(e: TxError) -> VestingError {
        match e {
            TxError::Vesting(v) => v,
            other => panic!("expected a vesting error, got {other:?}"),
        }
    }

    fn e(l: &Ledger, id: u8) -> &Entry {
        l.vesting().unwrap().get(&[id; 32]).unwrap()
    }

    #[test]
    fn a_claim_releases_exactly_what_has_vested_into_a_note_and_pays_the_proposer_the_base() {
        let mut l = ledger(vec![cfg(1, false)], 1_999);
        assert_eq!(verr(ap!(l, claim(&l, 1, 2 * BASE, 0, HOLDER, 1)).unwrap_err()), VestingError::NotYetVested { available: 0, want: 2 * BASE });
        l.set_timestamp_ms(4_000); // 2 000 ms into the linear period: 2 U
        assert_eq!(
            verr(ap!(l, claim(&l, 1, 2 * U + 1, 0, HOLDER, 1)).unwrap_err()),
            VestingError::NotYetVested { available: 2 * U, want: 2 * U + 1 }
        );
        let t = claim(&l, 1, 2 * U, 0, HOLDER, 1);
        let cm = l.derived_commitment(&t.action, &StubExecutor).unwrap();
        apply(&mut l, &t).unwrap();
        assert!(l.has_commitment(&cm), "the claim note is in the tree");
        assert_eq!(l.deposits().len(), 1);
        assert_eq!((e(&l, 1).claimed, e(&l, 1).nonce), (2 * U, 1));
        assert_eq!(l.validators().get(&kp(PROPOSER).address()).unwrap().rewards, BASE);
        assert_eq!(l.vesting().unwrap().released, 2 * U - BASE);
        let a = l.audit();
        assert!(a.invariant_holds(), "{a:?}");
        // The same claim again: its nonce is spent.
        assert_eq!(verr(apply(&mut l, &t).unwrap_err()), VestingError::BadNonce { expected: 1, actual: 0 });
        // Nothing more has vested since.
        assert!(matches!(verr(ap!(l, claim(&l, 1, 2 * BASE, 1, HOLDER, 2)).unwrap_err()), VestingError::NotYetVested { .. }));
    }

    #[test]
    fn a_claim_is_refused_for_every_bad_field() {
        let l = ledger(vec![cfg(1, false)], 20_000);
        let check = |t: Transaction| l.validate(&t, &StubExecutor).unwrap_err();
        assert_eq!(verr(check(claim(&l, 1, U, 0, REVOKERS[0], 1))), VestingError::BadSignature, "not the beneficiary's key");
        assert_eq!(verr(check(claim(&l, 2, U, 0, HOLDER, 1))), VestingError::UnknownEntry(hex::encode([2u8; 32])));
        assert_eq!(verr(check(claim(&l, 1, BASE, 0, HOLDER, 1))), VestingError::BelowBundleBase { amount: BASE, base: BASE });
        // The recipient is inside the signature: redirected after signing, it is refused.
        let mut redirected = claim(&l, 1, U, 0, HOLDER, 1);
        if let Action::ClaimVested { to, .. } = &mut redirected.action {
            to.pk[0] ^= 1;
        }
        assert_eq!(verr(check(redirected)), VestingError::BadSignature);
        let mut short = claim(&l, 1, U, 0, HOLDER, 1);
        if let Action::ClaimVested { to, .. } = &mut short.action {
            to.kem_ek.pop();
        }
        assert_eq!(verr(check(short)), VestingError::BadRecipient);
        // A note that already exists.
        let mut l2 = l.clone();
        let t = claim(&l2, 1, U, 0, HOLDER, 1);
        let cm = l2.derived_commitment(&t.action, &StubExecutor).unwrap();
        l2.deposit(cm, &StubExecutor).unwrap();
        assert_eq!(l2.validate(&t, &StubExecutor).unwrap_err(), TxError::CommitmentExists(cm));
        // No section, no vesting action at all.
        let mut plain = l.clone();
        plain.set_vesting(None);
        assert_eq!(plain.validate(&claim(&l, 1, U, 0, HOLDER, 1), &StubExecutor).unwrap_err(), TxError::UnsupportedAction("vesting"));
    }

    #[test]
    fn a_revoke_takes_only_the_unvested_part_and_freezes_the_entry() {
        let mut l = ledger(vec![cfg(1, true), cfg(2, false)], 5_000); // 3 U vested, 7 U not
        assert_eq!(verr(ap!(l, revoke(&l, 2, U, 0)).unwrap_err()), VestingError::NotRevocable);
        assert_eq!(
            verr(ap!(l, revoke_to(&l, 1, U, 0, addr(TREASURY), &[(0, HOLDER), (1, REVOKERS[1])])).unwrap_err()),
            VestingError::BadSignature
        );
        assert_eq!(
            verr(ap!(l, revoke(&l, 1, 7 * U + 1, 0)).unwrap_err()),
            VestingError::RevokeExceedsUnvested { unvested_now: 7 * U, want: 7 * U + 1 }
        );
        // The revokers sign a little less than they saw (the margin). The note carries that;
        // the revoke takes the whole unvested part.
        let t = revoke(&l, 1, 6 * U, 0);
        let cm = l.derived_commitment(&t.action, &StubExecutor).unwrap();
        assert_eq!(cm, crate::ledger::mint_commitment(&StubExecutor, &addr(TREASURY).pk, 6 * U - BASE, l.height() as u32, &[9; 8]));
        apply(&mut l, &t).unwrap();
        assert!(l.has_commitment(&cm), "the treasury's note is in the tree");
        assert_eq!((e(&l, 1).revoked_out, e(&l, 1).revoked_at, e(&l, 1).revoke_nonce, e(&l, 1).nonce), (6 * U, Some(5_000), 1, 0));
        assert!(l.audit().invariant_holds());
        // The same revoke again: its nonce is spent.
        assert_eq!(verr(apply(&mut l, &t).unwrap_err()), VestingError::BadNonce { expected: 1, actual: 0 });
        // Frozen at the 3 U that had vested, whatever the time: claimable at once, not a unit more.
        l.set_timestamp_ms(1_000_000);
        assert!(matches!(verr(ap!(l, claim(&l, 1, 3 * U + 1, 0, HOLDER, 1)).unwrap_err()), VestingError::NotYetVested { .. }));
        ap!(l, claim(&l, 1, 3 * U, 0, HOLDER, 1)).unwrap();
        // The seventh U is still in the register and is the treasury's: a second revoke pays
        // it out — exactly, since nothing moves it now — and then there is nothing left.
        assert_eq!((e(&l, 1).held(), unvested(e(&l, 1), 1_000_000)), (U, U));
        assert_eq!(
            verr(ap!(l, revoke(&l, 1, U + 1, 1)).unwrap_err()),
            VestingError::RevokeExceedsUnvested { unvested_now: U, want: U + 1 }
        );
        ap!(l, revoke(&l, 1, U, 1)).unwrap();
        assert_eq!((e(&l, 1).revoked_out, e(&l, 1).revoked_at, e(&l, 1).revoke_nonce), (7 * U, Some(5_000), 2), "the freeze stays where the first revoke put it");
        assert_eq!(verr(ap!(l, revoke(&l, 1, 2 * BASE, 2)).unwrap_err()), VestingError::AlreadyRevoked);
        assert_eq!(e(&l, 1).held(), 0);
        let a = l.audit();
        assert!(a.invariant_holds(), "{a:?}");
        assert_eq!(a.vesting_released, 10 * U - 3 * BASE, "one claim's and two revokes' notes");
        assert_eq!(a.vesting_in_register, 10 * U, "entry 2, untouched");
    }

    /// Audit v6, STAKE-3a: a revoke pays the treasury the entry names in genesis and no other
    /// address. Before, `check_revoke` tested the revoker's signature, the nonce and the amount,
    /// and the recipient was whatever the revoker signed: one key could send the unvested part
    /// of every revocable entry to an address of its holder's choosing.
    #[test]
    fn a_revoke_to_any_address_but_the_treasury_is_refused() {
        let mut l = ledger(vec![cfg(1, true)], 5_000);
        let quorum = [(0, REVOKERS[0]), (1, REVOKERS[1]), (2, REVOKERS[2])];
        let before = l.state_root();
        // Every revoker signs it, rightfully: the destination is still not theirs to choose.
        for to in [addr(78), addr(HOLDER), addr(REVOKERS[0])] {
            let t = revoke_to(&l, 1, 6 * U, 0, to, &quorum);
            assert_eq!(verr(l.validate(&t, &StubExecutor).unwrap_err()), VestingError::NotTheTreasury, "admission");
            assert_eq!(verr(apply(&mut l, &t).unwrap_err()), VestingError::NotTheTreasury, "apply");
        }
        // The treasury's owner key with another encapsulation key is another address: nobody
        // holding the treasury wallet could open a note sealed to it.
        let mut half = addr(TREASURY);
        half.kem_ek[0] ^= 1;
        assert_eq!(verr(ap!(l, revoke_to(&l, 1, 6 * U, 0, half, &quorum)).unwrap_err()), VestingError::NotTheTreasury);
        assert_eq!(l.state_root(), before, "nothing written");
        ap!(l, revoke_to(&l, 1, 6 * U, 0, addr(TREASURY), &quorum)).unwrap();
        assert_eq!(e(&l, 1).revoked_out, 6 * U);
    }

    /// Audit v6, STAKE-3b: the revoker is a set of keys with a threshold — here 2 of 3. One
    /// signature is refused, two are accepted, and a revoker who signs twice counts once (it is
    /// refused outright: a list naming one signer twice is not a quorum of two).
    #[test]
    fn a_revoke_needs_a_threshold_of_distinct_revokers() {
        let l = ledger(vec![cfg(1, true)], 5_000);
        let refused = |signers: &[(u8, u8)]| verr(l.validate(&revoke_to(&l, 1, 6 * U, 0, addr(TREASURY), signers), &StubExecutor).unwrap_err());
        let [a, b, c] = REVOKERS;
        assert_eq!(refused(&[]), VestingError::BelowThreshold { have: 0, need: 2 });
        // 1 of 3, whichever the one is.
        for one in [(0, a), (1, b), (2, c)] {
            assert_eq!(refused(&[one]), VestingError::BelowThreshold { have: 1, need: 2 });
        }
        // The same revoker twice: two valid signatures, one signer.
        assert_eq!(refused(&[(0, a), (0, a)]), VestingError::DuplicateRevoker(0));
        assert_eq!(refused(&[(1, b), (2, c), (1, b)]), VestingError::DuplicateRevoker(1));
        // One key signing under two positions: the second signature is not that position's key's.
        assert_eq!(refused(&[(0, a), (1, a)]), VestingError::BadSignature);
        // A position the list does not have, a key the list does not have, and the beneficiary.
        assert_eq!(refused(&[(0, a), (3, b)]), VestingError::BadRevokerIndex(3));
        assert_eq!(refused(&[(0, a), (1, 50)]), VestingError::BadSignature);
        assert_eq!(refused(&[(0, a), (1, HOLDER)]), VestingError::BadSignature);
        // A bad signature beside enough good ones is still a refusal.
        assert_eq!(refused(&[(0, a), (1, b), (2, 50)]), VestingError::BadSignature);
        // 2 of 3, any two, in any order; and all three.
        for quorum in [vec![(0, a), (1, b)], vec![(0, a), (2, c)], vec![(2, c), (1, b)], vec![(0, a), (1, b), (2, c)]] {
            let mut l = l.clone();
            ap!(l, revoke_to(&l, 1, 6 * U, 0, addr(TREASURY), &quorum)).unwrap_or_else(|e| panic!("{quorum:?}: {e:?}"));
            assert_eq!(e(&l, 1).revoked_out, 6 * U, "{quorum:?}");
        }
        // The signatures are over one message: a quorum gathered for one revoke is none for
        // another amount.
        let mut swapped = revoke(&l, 1, 6 * U, 0);
        if let Action::RevokeVesting { unvested, .. } = &mut swapped.action {
            *unvested = 7 * U;
        }
        assert_eq!(verr(l.validate(&swapped, &StubExecutor).unwrap_err()), VestingError::BadSignature);
    }

    /// Audit v6, STAKE-4: the revokers have their own nonce. Claims, revokes, bonds and unbonds
    /// of an entry shared one, so a beneficiary who saw a revoke in flight landed a claim of a
    /// little over the base first and the signed revoke went stale (`BadNonce`) — and again
    /// after every re-signing, each round a ceremony for the revokers and one cheap
    /// transaction for the holder.
    #[test]
    fn a_claim_in_flight_cannot_stale_a_revoke() {
        let mut l = ledger(vec![cfg(1, true)], 5_000); // 3 U vested, 7 U not
        let signed = revoke(&l, 1, 6 * U, 0);
        // The holder sees it pooled and lands three dust claims ahead of it.
        for n in 0..3 {
            ap!(l, claim(&l, 1, 2 * BASE, n, HOLDER, n as u8 + 1)).unwrap();
        }
        let r = apply(&mut l, &signed);
        assert!(r.is_ok(), "dust claims landed first and the signed revoke went stale: {r:?}");
        assert_eq!((e(&l, 1).revoked_out, e(&l, 1).revoked_at), (6 * U, Some(5_000)));
        assert!(l.audit().invariant_holds());
    }

    /// Audit v6, STAKE-4: a revoke takes the whole unvested part as of the block that applies
    /// it, whatever amount its note carries. The entry was frozen at `amount − revoked_out`, so
    /// whatever the revokers left out of the signed amount — the margin they sign under, or
    /// more — vested to the holder at once.
    #[test]
    fn nothing_is_left_to_vest_after_a_revoke() {
        let mut l = ledger(vec![cfg(1, true)], 5_000); // 3 U vested, 7 U not
        ap!(l, revoke(&l, 1, 6 * U, 0)).unwrap();
        for t in [5_000, 5_001, 12_000, 1_000_000] {
            assert_eq!(vested(e(&l, 1), t), 3 * U, "t = {t}: the revokers signed 6 U of 7 U and the seventh vested at once");
            assert_eq!(claimable(e(&l, 1), t, l.epoch()), 3 * U, "t = {t}");
        }
        l.set_timestamp_ms(1_000_000);
        assert!(matches!(verr(ap!(l, claim(&l, 1, 3 * U + 1, 0, HOLDER, 1)).unwrap_err()), VestingError::NotYetVested { .. }));
        ap!(l, claim(&l, 1, 3 * U, 0, HOLDER, 1)).unwrap();
        assert_eq!(claimable(e(&l, 1), u64::MAX, l.epoch()), 0, "the holder has everything that had vested, and nothing more ever does");
    }

    /// Review focus 1: a claim admitted against the head, a revoke landing first — the claim can
    /// only ever have asked for what had vested, which the frozen total always covers, and its
    /// nonce is the beneficiary's, which a revoke no longer spends (STAKE-4): it applies as
    /// signed.
    #[test]
    fn a_claim_admitted_before_a_revoke_still_applies_after_it() {
        let mut l = ledger(vec![cfg(1, true)], 5_000); // 3 U vested
        let c = claim(&l, 1, 3 * U, 0, HOLDER, 1);
        l.validate(&c, &StubExecutor).unwrap();
        ap!(l, revoke(&l, 1, 7 * U, 0)).unwrap();
        apply(&mut l, &c).unwrap();
        assert_eq!((e(&l, 1).nonce, e(&l, 1).revoke_nonce, e(&l, 1).held()), (1, 1, 0));
        assert!(l.audit().invariant_holds());
    }

    #[test]
    fn locked_ram_bonds_to_a_validator_and_comes_back_only_to_the_lock() {
        let v = kp(60);
        let mut l = ledger(vec![cfg(1, false), cfg(2, true)], 1_500); // nothing vested yet
        assert_eq!(verr(ap!(l, bond(&l, 2, &v, MIN_STAKE, 0, true)).unwrap_err()), VestingError::BondNeedsIrrevocable);
        assert!(matches!(
            ap!(l, bond(&l, 1, &v, MIN_STAKE - 1, 0, true)).unwrap_err(),
            TxError::Staking(StakingError::BelowMinStake { .. })
        ));
        assert_eq!(
            verr(ap!(l, bond(&l, 1, &v, 10 * U + 1, 0, true)).unwrap_err()),
            VestingError::NotFreeToBond { available: 10 * U, want: 10 * U + 1 }
        );
        // Locked, unvested RAND bonds: that is the point (SAFT Schedule 2 §4).
        let staked = 6 * U;
        assert!(staked >= MIN_STAKE);
        ap!(l, bond(&l, 1, &v, staked, 0, true)).unwrap();
        assert_eq!(l.validators().get(&v.address()).unwrap().stake, staked);
        assert_eq!((e(&l, 1).bonded, e(&l, 1).bonded_to), (staked, Some(v.address())));
        assert!(l.audit().invariant_holds(), "{:?}", l.audit());
        // Only one validator per entry at a time.
        assert_eq!(verr(ap!(l, bond(&l, 1, &kp(61), MIN_STAKE, 1, true)).unwrap_err()), VestingError::BondedElsewhere);
        // Fully vested now, but the bonded part is stake: only the rest is claimable.
        l.set_timestamp_ms(1_000_000);
        assert_eq!(
            verr(ap!(l, claim(&l, 1, 4 * U + 1, 1, HOLDER, 1)).unwrap_err()),
            VestingError::NotYetVested { available: 4 * U, want: 4 * U + 1 }
        );
        // The validator's own key cannot unbond stake the entry bonded.
        let own = crate::types::actions::unbond_message(CHAIN, &v.address(), BASE, 0);
        let t = tx(Action::Unbond { validator: v.address(), amount: BASE, nonce: 0, signature: v.sign(own.as_bytes()) });
        assert!(matches!(apply(&mut l, &t).unwrap_err(), TxError::Staking(StakingError::InsufficientStake { have: 0, .. })));
        // The beneficiary takes it back: out of the stake at once, claimable two epochs on.
        assert_eq!(verr(ap!(l, unbond(&l, 1, staked + 1, 1)).unwrap_err()), VestingError::NotBonded { bonded: staked, want: staked + 1 });
        ap!(l, unbond(&l, 1, staked, 1)).unwrap();
        assert_eq!(l.validators().get(&v.address()).unwrap().stake, 0);
        assert_eq!((e(&l, 1).bonded, e(&l, 1).bonded_to), (0, None));
        assert!(l.audit().invariant_holds(), "{:?}", l.audit());
        assert!(matches!(verr(ap!(l, claim(&l, 1, 4 * U + 1, 2, HOLDER, 1)).unwrap_err()), VestingError::NotYetVested { .. }));
        l.set_height(l.height() + 2 * 4 * staking::UNBONDING_EPOCHS);
        ap!(l, claim(&l, 1, 10 * U, 2, HOLDER, 1)).unwrap();
        assert!(e(&l, 1).unbonding.is_empty(), "the released row is settled");
        let a = l.audit();
        assert!(a.invariant_holds(), "{a:?}");
        assert_eq!(e(&l, 1).in_register(), 0);
        assert_eq!(a.vesting_in_register, 10 * U, "entry 2, untouched");
    }

    /// The v0.6 rescan's lead "vesting actions don't bound the note `time`", refuted and pinned: a
    /// claim or a revoke whose note `time` lies outside `[height - TIME_WINDOW, height]` — signed
    /// by the rightful key, every other field valid — is refused `TimeOutOfWindow` at admission and
    /// at apply, and the ledger is untouched; the window's two edges pass the time rule. The
    /// bound is `check_time`'s match listing `ClaimVested` and `RevokeVesting`: drop either arm
    /// and this goes red.
    #[test]
    fn a_vesting_note_time_outside_the_window_is_refused() {
        use crate::ledger::TIME_WINDOW;
        let mut l = ledger(vec![cfg(1, true)], 20_000);
        l.set_height(TIME_WINDOW + 10);
        let h = l.height() as u32;
        let claim_at = |l: &Ledger, time: u32| {
            let (to, r) = (addr(HOLDER), [1u32; 8]);
            let m = claim_vested_message(&g(l), CHAIN, &[1; 32], U, 0, &to, time, &r, &env());
            let signature = kp(HOLDER).sign(m.as_bytes());
            tx(Action::ClaimVested { entry: [1; 32], amount: U, nonce: 0, to, time, r, envelope: env(), signature })
        };
        let revoke_at = |l: &Ledger, time: u32| {
            let (to, r) = (addr(TREASURY), [9u32; 8]);
            let m = revoke_vesting_message(&g(l), CHAIN, &[1; 32], U, 0, &to, time, &r, &env());
            let signatures = (0..2u8).map(|i| RevokerSignature { index: i, signature: kp(REVOKERS[i as usize]).sign(m.as_bytes()) }).collect();
            tx(Action::RevokeVesting { entry: [1; 32], unvested: U, nonce: 0, to, time, r, envelope: env(), signatures })
        };
        let out = [h + 1, h + 1000, u32::MAX, h - TIME_WINDOW as u32 - 1, 0];
        for time in out {
            for t in [claim_at(&l, time), revoke_at(&l, time)] {
                let before = l.state_root();
                assert!(matches!(l.validate(&t, &StubExecutor), Err(TxError::TimeOutOfWindow { .. })), "time {time}: admission");
                assert!(matches!(apply(&mut l, &t), Err(TxError::TimeOutOfWindow { .. })), "time {time}: apply");
                assert_eq!(l.state_root(), before, "time {time}: nothing written");
            }
        }
        // The window's edges are inside it: whatever else a transaction fails, it is not the time.
        for time in [h, h - TIME_WINDOW as u32] {
            for t in [claim_at(&l, time), revoke_at(&l, time)] {
                let r = l.validate(&t, &StubExecutor);
                assert!(!matches!(r, Err(TxError::TimeOutOfWindow { .. })), "time {time}: {r:?}");
            }
        }
        // A claim at the window's upper edge goes through end to end.
        let ok = claim_at(&l, h);
        apply(&mut l, &ok).expect("an in-window claim applies");
    }
}
