//! Genesis vesting (`docs/superpowers/specs/2026-09-28-genesis-vesting-design.md`): timelocked
//! RAND for the team, investors and founding partners.
//!
//! A shielded note cannot be held back — a spend proof hides which note it consumes — so a
//! locked allocation lives *outside* the pool, in this public register seeded by the genesis
//! `vesting` section, and enters the pool only as it unlocks: a `ClaimVested` (signed by the
//! entry's beneficiary) pays the unlocked part into a note, a `RevokeVesting` (signed by the
//! entry's revoker) pays the unvested part to a treasury note and freezes the entry. The
//! schedule is a cliff, then linear, on the applying block's timestamp.
//!
//! Genesis-gated: a chain without the section has no register (`Ledger::vesting` is `None`)
//! and every one of the two actions is refused `UnsupportedAction("vesting")`.

use crate::crypto::{merkle_root, Hash, PublicKey, PUBLIC_KEY_LEN};
use serde::{Deserialize, Serialize};

/// What an allocation is for. Reporting only (`rand_getVestingSummary`): no rule reads it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Class {
    Team,
    Investor,
    Partner,
    Other,
}

impl Class {
    pub fn as_str(&self) -> &'static str {
        match self {
            Class::Team => "team",
            Class::Investor => "investor",
            Class::Partner => "partner",
            Class::Other => "other",
        }
    }

    fn byte(&self) -> u8 {
        match self {
            Class::Team => 0,
            Class::Investor => 1,
            Class::Partner => 2,
            Class::Other => 3,
        }
    }
}

/// One allocation as the genesis file lists it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VestingEntryConfig {
    /// 32 bytes, 64 hex characters; chosen at random by the cut tooling. Never a name.
    #[serde(with = "crate::bridge::state::hex_bytes32")]
    pub id: [u8; 32],
    pub class: Class,
    /// The Dilithium2 key that signs claims — generated by the holder, who sends only this.
    pub beneficiary: PublicKey,
    /// The Dilithium2 key that may revoke the unvested part. Absent: irrevocable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoker: Option<PublicKey>,
    /// Total, in units (1 RAND = 10⁹), a decimal string in the file like every genesis amount
    /// (a plain number is accepted on the way in).
    #[serde(with = "crate::ledger::staking::amount_string")]
    pub amount: u64,
    /// When the lockup starts (network launch, for a sale round).
    pub start_ms: u64,
    /// Nothing unlocks before `start + cliff`.
    pub cliff_ms: u64,
    /// The linear period, *after* the cliff (the SAFT's "C-month cliff, then L-month linear").
    pub linear_ms: u64,
    /// Optional tranche length: unlocks in whole steps (a month for the SAFT's monthly release)
    /// rather than continuously. Must divide `linear_ms`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub step_ms: Option<u64>,
}

/// The genesis `vesting` section.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VestingConfig {
    pub entries: Vec<VestingEntryConfig>,
}

impl VestingConfig {
    /// Every rule a file has to meet before it can seed a register; `Ok` is `Σ amount`.
    pub fn check(&self) -> Result<u64, String> {
        if self.entries.is_empty() {
            return Err("no entries".into());
        }
        let mut ids = std::collections::BTreeSet::new();
        let mut total: u64 = 0;
        for e in &self.entries {
            let id = hex::encode(e.id);
            if !ids.insert(e.id) {
                return Err(format!("entry {id} listed twice"));
            }
            if e.amount == 0 {
                return Err(format!("entry {id}: zero amount"));
            }
            if let Some(step) = e.step_ms {
                if step == 0 || e.linear_ms == 0 || e.linear_ms % step != 0 {
                    return Err(format!("entry {id}: the step must be non-zero and divide the linear period"));
                }
            }
            if e.start_ms.checked_add(e.cliff_ms).and_then(|c| c.checked_add(e.linear_ms)).is_none() {
                return Err(format!("entry {id}: start + cliff + linear overflows"));
            }
            if e.beneficiary.as_bytes().len() != PUBLIC_KEY_LEN {
                return Err(format!("entry {id}: beneficiary key is not a Dilithium2 public key"));
            }
            if let Some(r) = &e.revoker {
                if r.as_bytes().len() != PUBLIC_KEY_LEN {
                    return Err(format!("entry {id}: revoker key is not a Dilithium2 public key"));
                }
                if r == &e.beneficiary {
                    return Err(format!("entry {id}: the beneficiary cannot be its own revoker"));
                }
            }
            total = total.checked_add(e.amount).ok_or_else(|| "the entries' total overflows".to_string())?;
        }
        Ok(total)
    }
}

/// One allocation in the register: its genesis terms plus what has happened to it since.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry {
    #[serde(with = "crate::bridge::state::hex_bytes32")]
    pub id: [u8; 32],
    pub class: Class,
    pub beneficiary: PublicKey,
    #[serde(default)]
    pub revoker: Option<PublicKey>,
    pub amount: u64,
    pub start_ms: u64,
    pub cliff_ms: u64,
    pub linear_ms: u64,
    #[serde(default)]
    pub step_ms: Option<u64>,
    /// Released to the beneficiary so far, gross (each claim's base included).
    #[serde(default)]
    pub claimed: u64,
    /// The unvested part a revoke paid to the treasury, gross; 0 until revoked.
    #[serde(default)]
    pub revoked_out: u64,
    /// The timestamp of the block that applied the revoke.
    #[serde(default)]
    pub revoked_at: Option<u64>,
    /// What of this entry is bonded as validator stake right now (`BondVested`): still locked,
    /// counted in the validator's `stake`, never claimable until unbonded. Irrevocable entries
    /// only.
    #[serde(default)]
    pub bonded: u64,
    /// The validator `bonded` sits with; `None` whenever `bonded` is 0.
    #[serde(default)]
    pub bonded_to: Option<crate::crypto::Address>,
    /// `UnbondVested` amounts on their way back to the lock, `(release_epoch, amount)`: out of
    /// the validator's stake, not yet claimable (the register's `UNBONDING_EPOCHS`, as a plain
    /// unbond waits). Dropped by the entry's next action once released.
    #[serde(default)]
    pub unbonding: Vec<(u64, u64)>,
    /// Bumped by every accepted vesting action on the entry: the replay protection.
    #[serde(default)]
    pub nonce: u64,
}

impl Entry {
    fn from_config(c: &VestingEntryConfig) -> Entry {
        Entry {
            id: c.id,
            class: c.class,
            beneficiary: c.beneficiary.clone(),
            revoker: c.revoker.clone(),
            amount: c.amount,
            start_ms: c.start_ms,
            cliff_ms: c.cliff_ms,
            linear_ms: c.linear_ms,
            step_ms: c.step_ms,
            claimed: 0,
            revoked_out: 0,
            revoked_at: None,
            bonded: 0,
            bonded_to: None,
            unbonding: Vec::new(),
            nonce: 0,
        }
    }

    /// What still belongs to this entry: neither claimed nor revoked out — whether it sits in
    /// the register or is bonded as a validator's stake.
    pub fn held(&self) -> u64 {
        self.amount.saturating_sub(self.claimed).saturating_sub(self.revoked_out)
    }

    /// What the register itself holds for this entry: `held` less what is bonded (which the
    /// validator register counts). The supply audit's vesting half.
    pub fn in_register(&self) -> u64 {
        self.held().saturating_sub(self.bonded)
    }

    /// What is in the register and free to leave it at `epoch`: not bonded, not still
    /// unbonding.
    pub fn free(&self, epoch: u64) -> u64 {
        let waiting = self.unbonding.iter().filter(|(e, _)| *e > epoch).fold(0u64, |a, (_, v)| a.saturating_add(*v));
        self.in_register().saturating_sub(waiting)
    }

    fn leaf(&self) -> Hash {
        let mut b = Vec::with_capacity(32 + 1 + 2 * PUBLIC_KEY_LEN + 8 * 9);
        b.extend_from_slice(&self.id);
        b.push(self.class.byte());
        b.extend_from_slice(self.beneficiary.as_bytes());
        match &self.revoker {
            Some(r) => {
                b.push(1);
                b.extend_from_slice(r.as_bytes());
            }
            None => b.push(0),
        }
        for w in [self.amount, self.start_ms, self.cliff_ms, self.linear_ms, self.step_ms.unwrap_or(0), self.claimed, self.revoked_out, self.bonded] {
            b.extend_from_slice(&w.to_be_bytes());
        }
        match &self.bonded_to {
            Some(v) => {
                b.push(1);
                b.extend_from_slice(v.as_bytes());
            }
            None => b.push(0),
        }
        b.extend_from_slice(&(self.unbonding.len() as u64).to_be_bytes());
        for (e, v) in &self.unbonding {
            b.extend_from_slice(&e.to_be_bytes());
            b.extend_from_slice(&v.to_be_bytes());
        }
        match self.revoked_at {
            Some(t) => {
                b.push(1);
                b.extend_from_slice(&t.to_be_bytes());
            }
            None => b.push(0),
        }
        b.extend_from_slice(&self.nonce.to_be_bytes());
        Hash::digest_domain(b"rand-vesting-leaf-1", &b)
    }
}

/// The schedule, the SAFT's shape: nothing until `start + cliff`; then `linear` more, either
/// continuously or in whole `step`s (a step unlocks at the *end* of its period, so a 12-month
/// cliff and 18 monthly steps release 1/18 at months 13, 14, …, 30). A revoked entry is frozen
/// at `amount − revoked_out`, whatever the time.
pub fn vested(e: &Entry, t_ms: u64) -> u64 {
    if e.revoked_at.is_some() {
        return e.amount.saturating_sub(e.revoked_out);
    }
    let cliff = e.start_ms.saturating_add(e.cliff_ms);
    if t_ms < cliff {
        return 0;
    }
    let elapsed = t_ms - cliff;
    if elapsed >= e.linear_ms {
        return e.amount;
    }
    let elapsed = match e.step_ms {
        Some(step) if step > 0 => elapsed - elapsed % step,
        _ => elapsed,
    };
    // elapsed < linear, so the quotient is below `amount` and fits a u64.
    ((e.amount as u128 * elapsed as u128) / e.linear_ms as u128) as u64
}

/// What the beneficiary may claim at `t_ms` in `epoch`: vested and not yet claimed, and in the
/// register and free to leave it (bonded or still-unbonding RAND must come back first).
pub fn claimable(e: &Entry, t_ms: u64, epoch: u64) -> u64 {
    vested(e, t_ms).saturating_sub(e.claimed).min(e.free(epoch))
}

/// What a revoke at `t_ms` could take: the part not yet vested (0 once revoked).
pub fn unvested(e: &Entry, t_ms: u64) -> u64 {
    if e.revoked_at.is_some() {
        return 0;
    }
    e.amount.saturating_sub(vested(e, t_ms))
}

/// The register: every entry, in id order, and the net value its claims and revokes have put
/// into the pool (the supply audit's `vesting_released`). Persisted whole, as JSON.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct VestingRegister {
    pub entries: Vec<Entry>,
    /// Σ of the notes claims and revokes created (net of each one's base).
    #[serde(default)]
    pub released: u64,
}

impl VestingRegister {
    pub fn from_config(c: &VestingConfig) -> VestingRegister {
        let mut entries: Vec<Entry> = c.entries.iter().map(Entry::from_config).collect();
        entries.sort_by(|a, b| a.id.cmp(&b.id));
        VestingRegister { entries, released: 0 }
    }

    pub fn get(&self, id: &[u8; 32]) -> Option<&Entry> {
        self.entries.binary_search_by(|e| e.id.cmp(id)).ok().map(|i| &self.entries[i])
    }

    pub fn get_mut(&mut self, id: &[u8; 32]) -> Option<&mut Entry> {
        self.entries.binary_search_by(|e| e.id.cmp(id)).ok().map(move |i| &mut self.entries[i])
    }

    /// What genesis issued into the register.
    pub fn issued(&self) -> u64 {
        self.entries.iter().fold(0u64, |a, e| a.saturating_add(e.amount))
    }

    /// What the register itself holds (bonded RAND is in the validator register's total).
    pub fn in_register(&self) -> u64 {
        self.entries.iter().fold(0u64, |a, e| a.saturating_add(e.in_register()))
    }

    /// What is bonded out of the register to `validator` — stake its own `Unbond` may not touch.
    pub fn bonded_to(&self, validator: &crate::crypto::Address) -> u64 {
        self.entries
            .iter()
            .filter(|e| e.bonded_to.as_ref() == Some(validator))
            .fold(0u64, |a, e| a.saturating_add(e.bonded))
    }

    /// The register's contribution to the state root: its entries' leaves in id order, then
    /// the released counter.
    pub fn root(&self) -> Hash {
        let leaves: Vec<Hash> = self.entries.iter().map(Entry::leaf).collect();
        let mut b = merkle_root(&leaves).as_bytes().to_vec();
        b.extend_from_slice(&(self.entries.len() as u64).to_be_bytes());
        b.extend_from_slice(&self.released.to_be_bytes());
        Hash::digest_domain(b"rand-vesting-root-1", &b)
    }
}

/// Why a vesting action was refused.
#[derive(Debug, thiserror::Error, PartialEq, Eq, Clone)]
pub enum VestingError {
    #[error("vesting entry {0} is not in the register")]
    UnknownEntry(String),
    #[error("wrong nonce: expected {expected}, got {actual}")]
    BadNonce { expected: u64, actual: u64 },
    #[error("bad vesting signature")]
    BadSignature,
    #[error("{amount} does not cover the bundle base {base}")]
    BelowBundleBase { amount: u64, base: u64 },
    #[error("only {available} is vested and unclaimed, cannot claim {want}")]
    NotYetVested { available: u64, want: u64 },
    #[error("the entry has no revoker")]
    NotRevocable,
    #[error("the entry is already revoked")]
    AlreadyRevoked,
    #[error("only {unvested_now} is unvested, cannot revoke {want}")]
    RevokeExceedsUnvested { unvested_now: u64, want: u64 },
    #[error("bad recipient address")]
    BadRecipient,
    #[error("only an irrevocable entry may bond")]
    BondNeedsIrrevocable,
    #[error("the entry is bonded to another validator")]
    BondedElsewhere,
    #[error("only {available} is free to bond, cannot bond {want}")]
    NotFreeToBond { available: u64, want: u64 },
    #[error("only {bonded} is bonded, cannot unbond {want}")]
    NotBonded { bonded: u64, want: u64 },
    #[error("amount must not be zero")]
    ZeroAmount,
    #[error("arithmetic overflow")]
    Overflow,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::{Address, Keypair};

    pub(crate) fn key(i: u8) -> PublicKey {
        Keypair::from_seed([i; 32]).unwrap().public_key().clone()
    }

    fn cfg(id: u8, amount: u64, start: u64, cliff: u64, linear: u64) -> VestingEntryConfig {
        VestingEntryConfig {
            id: [id; 32],
            class: Class::Investor,
            beneficiary: key(1),
            revoker: Some(key(2)),
            amount,
            start_ms: start,
            cliff_ms: cliff,
            linear_ms: linear,
            step_ms: None,
        }
    }

    fn entry(amount: u64, start: u64, cliff: u64, linear: u64) -> Entry {
        Entry::from_config(&cfg(1, amount, start, cliff, linear))
    }

    #[test]
    fn nothing_vests_before_the_cliff_and_the_linear_period_runs_after_it() {
        // 1 200 000 from t = 10 000: a 12 000 ms cliff, then 24 000 ms linear.
        let e = entry(1_200_000, 10_000, 12_000, 24_000);
        assert_eq!(vested(&e, 0), 0);
        assert_eq!(vested(&e, 21_999), 0, "one ms before the cliff");
        assert_eq!(vested(&e, 22_000), 0, "the linear period starts at the cliff");
        assert_eq!(vested(&e, 22_001), 50);
        assert_eq!(vested(&e, 34_000), 600_000, "half way through the linear period");
        assert_eq!(vested(&e, 45_999), 1_199_950);
        assert_eq!(vested(&e, 46_000), 1_200_000);
        assert_eq!(vested(&e, u64::MAX), 1_200_000);
    }

    /// SAFT Schedule 2 §2, the Founding Sale: a 12-month cliff, then 18 monthly tranches that
    /// unlock at months 13 through 30.
    #[test]
    fn monthly_steps_release_one_tranche_at_the_end_of_each_month_after_the_cliff() {
        const MONTH: u64 = 30 * 86_400_000;
        let mut c = cfg(1, 18_000, 0, 12 * MONTH, 18 * MONTH);
        c.step_ms = Some(MONTH);
        let e = Entry::from_config(&c);
        assert_eq!(vested(&e, 12 * MONTH), 0, "month 12: still nothing");
        assert_eq!(vested(&e, 13 * MONTH - 1), 0);
        assert_eq!(vested(&e, 13 * MONTH), 1_000, "month 13: the first tranche");
        assert_eq!(vested(&e, 14 * MONTH - 1), 1_000);
        assert_eq!(vested(&e, 21 * MONTH), 9_000);
        assert_eq!(vested(&e, 30 * MONTH - 1), 17_000);
        assert_eq!(vested(&e, 30 * MONTH), 18_000, "month 30: the last");
    }

    #[test]
    fn a_zero_cliff_with_a_zero_linear_period_unlocks_at_the_start() {
        let e = entry(100, 5, 0, 0);
        assert_eq!(vested(&e, 4), 0);
        assert_eq!(vested(&e, 5), 100);
    }

    #[test]
    fn the_schedule_does_not_overflow_near_u64_max() {
        let e = entry(u64::MAX, 0, 0, 1_000);
        assert_eq!(vested(&e, 500), u64::MAX / 2);
        assert_eq!(vested(&e, 999), ((u64::MAX as u128 * 999) / 1000) as u64);
    }

    #[test]
    fn a_revoked_entry_is_frozen_and_claimable_counts_what_was_claimed() {
        let mut e = entry(1_000, 0, 0, 1_000);
        e.claimed = 100;
        assert_eq!(claimable(&e, 300, 0), 200);
        assert_eq!(unvested(&e, 300), 700);
        e.revoked_at = Some(300);
        e.revoked_out = 650;
        assert_eq!(vested(&e, 300), 350);
        assert_eq!(vested(&e, 10_000), 350, "frozen, whatever the time");
        assert_eq!(claimable(&e, 10_000, 0), 250);
        assert_eq!(unvested(&e, 10_000), 0);
        assert_eq!(e.held(), 250);
    }

    #[test]
    fn bonded_and_unbonding_ram_is_not_claimable_until_it_is_back() {
        let mut e = entry(1_000, 0, 0, 1_000);
        e.bonded = 600;
        assert_eq!((e.held(), e.in_register(), e.free(0)), (1_000, 400, 400));
        assert_eq!(claimable(&e, 2_000, 0), 400, "fully vested, but 600 is stake");
        e.bonded = 100;
        e.unbonding = vec![(5, 500)];
        assert_eq!(claimable(&e, 2_000, 4), 400, "the 500 is still unbonding in epoch 4");
        assert_eq!(claimable(&e, 2_000, 5), 900, "released in epoch 5");
    }

    #[test]
    fn the_config_check_refuses_every_bad_entry() {
        let ok = VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5), cfg(2, 20, 0, 5, 5)] };
        assert_eq!(ok.check(), Ok(30));
        let bad = |c: VestingConfig, what: &str| {
            let e = c.check().unwrap_err();
            assert!(e.contains(what), "{e:?} should mention {what:?}");
        };
        bad(VestingConfig { entries: vec![] }, "no entries");
        bad(VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5), cfg(1, 20, 0, 0, 5)] }, "twice");
        bad(VestingConfig { entries: vec![cfg(1, 0, 0, 0, 5)] }, "zero amount");
        let mut stepped = cfg(1, 10, 0, 0, 5);
        stepped.step_ms = Some(2);
        bad(VestingConfig { entries: vec![stepped.clone()] }, "divide");
        stepped.step_ms = Some(0);
        bad(VestingConfig { entries: vec![stepped] }, "divide");
        bad(VestingConfig { entries: vec![cfg(1, 10, u64::MAX, 1, 0)] }, "overflows");
        bad(VestingConfig { entries: vec![cfg(1, u64::MAX, 0, 0, 5), cfg(2, 1, 0, 0, 5)] }, "total overflows");
        let mut short = cfg(1, 10, 0, 0, 5);
        short.beneficiary = serde_json::from_str::<PublicKey>("\"abcd\"").unwrap();
        bad(VestingConfig { entries: vec![short] }, "beneficiary key");
        let mut short = cfg(1, 10, 0, 0, 5);
        short.revoker = Some(serde_json::from_str::<PublicKey>("\"abcd\"").unwrap());
        bad(VestingConfig { entries: vec![short] }, "revoker key");
        let mut own = cfg(1, 10, 0, 0, 5);
        own.revoker = Some(own.beneficiary.clone());
        bad(VestingConfig { entries: vec![own] }, "its own revoker");
    }

    #[test]
    fn the_register_sorts_by_id_and_its_root_moves_with_every_field() {
        let c = VestingConfig { entries: vec![cfg(9, 10, 0, 0, 5), cfg(3, 20, 0, 0, 5)] };
        let r = VestingRegister::from_config(&c);
        assert_eq!(r.entries[0].id, [3; 32]);
        assert_eq!(r.get(&[9; 32]).unwrap().amount, 10);
        assert!(r.get(&[4; 32]).is_none());
        assert_eq!((r.issued(), r.in_register()), (30, 30));
        let base = r.root();
        let mutations: Vec<fn(&mut VestingRegister)> = vec![
            |r| r.entries[0].claimed += 1,
            |r| r.entries[0].revoked_out += 1,
            |r| r.entries[0].revoked_at = Some(0),
            |r| r.entries[0].nonce += 1,
            |r| r.entries[0].amount += 1,
            |r| r.entries[0].start_ms += 1,
            |r| r.entries[0].cliff_ms += 1,
            |r| r.entries[0].linear_ms += 1,
            |r| r.entries[0].step_ms = Some(1),
            |r| r.entries[0].class = Class::Team,
            |r| r.entries[0].revoker = None,
            |r| r.entries[0].beneficiary = key(7),
            |r| r.entries[0].bonded += 1,
            |r| r.entries[0].bonded_to = Some(Address([1; 32])),
            |r| r.entries[0].unbonding.push((1, 1)),
            |r| r.released += 1,
        ];
        for (i, m) in mutations.into_iter().enumerate() {
            let mut x = r.clone();
            m(&mut x);
            assert_ne!(x.root(), base, "mutation {i} must move the root");
        }
    }

    #[test]
    fn the_genesis_form_round_trips_as_json() {
        let c = VestingConfig { entries: vec![cfg(1, 10, 0, 0, 5)] };
        let json = serde_json::to_string(&c).unwrap();
        assert!(json.contains("\"class\":\"investor\""));
        assert!(!json.contains("step_ms"), "an absent step is omitted");
        assert_eq!(serde_json::from_str::<VestingConfig>(&json).unwrap(), c);
        let r = VestingRegister::from_config(&c);
        assert_eq!(serde_json::from_str::<VestingRegister>(&serde_json::to_string(&r).unwrap()).unwrap(), r);
    }
}
